"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Controller, useForm, type UseFormRegisterReturn } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";
import { AlertCircle, CheckCircle2, ChevronLeft, ChevronRight, Eye, FilePlus2, ImagePlus, Loader2, Search, X } from "lucide-react";
import { createClient } from "@/utils/supabase/client";

const PAGE_SIZE = 10;
const schema = z.object({
  aadhaarNumber: z.string().regex(/^\d{12}$/, "Enter a valid 12-digit Aadhaar number"),
  guardianRelation: z.enum(["Father", "Husband", "Guardian"]),
  guardianName: z.string().min(2, "Relative name is required"),
  hindiGuardianName: z.string().min(2, "Hindi relative name is required"),
  fullName: z.string().min(2, "Full name is required"),
  hindiName: z.string().min(2, "Hindi full name is required"),
  houseNo: z.string().min(1, "House number is required"),
  hindiHouseNo: z.string().min(1, "Hindi house is required"),
  locality: z.string().min(2, "Gali/locality is required"),
  hindiLocality: z.string().min(2, "Hindi locality is required"),
  policeStation: z.string().min(2, "Police station is required"),
  hindiPoliceStation: z.string().min(2, "Hindi police station is required"),
  postOffice: z.string().min(2, "Post office is required"),
  hindiPostOffice: z.string().min(2, "Hindi post is required"),
  city: z.string().min(2, "City is required"),
  hindiCity: z.string().min(2, "Hindi city is required"), state: z.string().min(2, "State is required"),
  hindiState: z.string().min(2, "Hindi state is required"),
  pincode: z.string().regex(/^\d{6}$/, "Enter a valid 6-digit pincode"),
  dob: z.string().min(1, "Date of birth is required").refine(value => !value || new Date(`${value}T00:00:00`) <= new Date(), "Date of birth cannot be in the future"),
  gender: z.enum(["Female", "Male", "Other"]),
  photo: z.custom<FileList>(value => typeof FileList !== "undefined" && value instanceof FileList, "Photo is required").refine(f => f.length === 1, "Photo is required").refine(f => !f[0] || f[0].size <= 5 * 1024 * 1024, "Photo must be 5 MB or smaller").refine(f => !f[0] || f[0].type.startsWith("image/"), "Select an image file"),
});
type FormValues = z.infer<typeof schema>;
type DocumentRow = { id:string; document_data:Partial<FormValues>; credits_used:number; status:string; created_at:string };

export default function GeneratePage() {
  const supabase = useMemo(() => createClient(), []);
  const [documents,setDocuments]=useState<DocumentRow[]>([]), [search,setSearch]=useState(""), [query,setQuery]=useState("");
  const [page,setPage]=useState(1), [count,setCount]=useState(0); const [loading,setLoading]=useState(true), [modalOpen,setModalOpen]=useState(false);
  const [message,setMessage]=useState<{type:"success"|"error";text:string}|null>(null);
  const loadDocuments=useCallback(async()=>{setLoading(true);const from=(page-1)*PAGE_SIZE;let request=supabase.from("generated_documents").select("id,document_data,credits_used,status,created_at",{count:"exact"}).order("created_at",{ascending:false}).range(from,from+PAGE_SIZE-1);if(query)request=request.ilike("document_data->>fullName",`%${query}%`);const {data,error,count:total}=await request;if(error)setMessage({type:"error",text:error.message});else{setDocuments((data as DocumentRow[])??[]);setCount(total??0)}setLoading(false)},[page,query,supabase]);
  useEffect(()=>{const timer=window.setTimeout(()=>void loadDocuments(),0);return()=>window.clearTimeout(timer)},[loadDocuments]);
  useEffect(()=>{const timer=window.setTimeout(()=>{setPage(1);setQuery(search.trim())},300);return()=>window.clearTimeout(timer)},[search]);
  const totalPages=Math.max(1,Math.ceil(count/PAGE_SIZE));
  return <div className="mx-auto max-w-7xl">
    <div className="mb-6"><h2 className="text-2xl font-bold">Generated IDs</h2><p className="mt-1 text-sm text-slate-500">Create and manage your generated records. Each submission costs 1 credit (₹10).</p></div>
    {message&&<div className={`mb-5 flex items-center justify-between rounded-xl border p-4 text-sm ${message.type==="success"?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-red-200 bg-red-50 text-red-800"}`} role="status"><span className="flex items-center gap-2">{message.type==="success"?<CheckCircle2 className="h-5"/>:<AlertCircle className="h-5"/>}{message.text}</span><button type="button" onClick={()=>setMessage(null)} aria-label="Dismiss"><X className="h-4"/></button></div>}
    <section className="card overflow-hidden">
      <div className="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between"><label className="relative block w-full sm:max-w-md"><span className="sr-only">Search by full name</span><Search className="pointer-events-none absolute left-3 top-1/2 h-5 -translate-y-1/2 text-slate-400"/><input className="field pl-10" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by full name..."/></label><button type="button" className="btn btn-primary shrink-0" onClick={()=>setModalOpen(true)}><FilePlus2 className="h-5"/>Generate ID</button></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-4">Full name</th><th className="p-4">Aadhaar no.</th><th className="p-4">Date of birth</th><th className="p-4">Gender</th><th className="p-4">Status</th><th className="p-4">Created</th><th className="p-4 text-right">Action</th></tr></thead><tbody>
        {loading?<tr><td colSpan={7} className="p-14 text-center text-slate-500"><Loader2 className="mx-auto mb-2 h-6 animate-spin"/>Loading records...</td></tr>:documents.length?documents.map(d=>{const v=d.document_data??{};return <tr className="border-t border-slate-100" key={d.id}><td className="p-4 font-semibold">{v.fullName||"—"}</td><td className="p-4 font-mono text-slate-600">{maskAadhaar(v.aadhaarNumber)}</td><td className="p-4 text-slate-600">{formatDate(v.dob)}</td><td className="p-4 text-slate-600">{v.gender||"—"}</td><td className="p-4"><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold capitalize text-emerald-700">{d.status}</span></td><td className="p-4 text-slate-500">{new Date(d.created_at).toLocaleDateString("en-IN")}</td><td className="p-4 text-right"><Link href={`/dashboard/generate/${d.id}`} className="inline-flex items-center gap-1.5 rounded-lg border border-indigo-200 px-3 py-2 text-xs font-bold text-indigo-700 hover:bg-indigo-50"><Eye className="h-4"/>View details</Link></td></tr>}):<tr><td colSpan={7} className="p-16 text-center"><FilePlus2 className="mx-auto mb-3 h-9 text-slate-300"/><p className="font-semibold">{query?"No matching records":"No generated IDs yet"}</p><p className="mt-1 text-sm text-slate-500">{query?"Try a different full name.":"Use Generate ID to create your first record."}</p></td></tr>}
      </tbody></table></div>
      <div className="flex flex-col gap-3 border-t border-slate-100 px-5 py-4 text-sm sm:flex-row sm:items-center sm:justify-between"><p className="text-slate-500">{count?`Showing ${(page-1)*PAGE_SIZE+1}–${Math.min(page*PAGE_SIZE,count)} of ${count}`:"0 records"}</p><div className="flex items-center gap-2"><button type="button" className="btn border border-slate-200 bg-white px-3 py-2" disabled={page===1||loading} onClick={()=>setPage(v=>v-1)}><ChevronLeft className="h-4"/>Previous</button><span className="px-2 font-semibold">Page {page} of {totalPages}</span><button type="button" className="btn border border-slate-200 bg-white px-3 py-2" disabled={page>=totalPages||loading} onClick={()=>setPage(v=>v+1)}>Next<ChevronRight className="h-4"/></button></div></div>
    </section>
    {modalOpen&&<GenerateModal onClose={()=>setModalOpen(false)} onCreated={async()=>{setModalOpen(false);setPage(1);setMessage({type:"success",text:"ID record generated successfully. 1 credit (₹10) was deducted."});await loadDocuments()}}/>}
  </div>
}

function GenerateModal({onClose,onCreated}:{onClose:()=>void;onCreated:()=>Promise<void>}) {
  const supabase=useMemo(()=>createClient(),[]);const {register,control,handleSubmit,reset,formState:{errors,isSubmitting}}=useForm<FormValues>({resolver:zodResolver(schema),defaultValues:{dob:"",gender:"Female",guardianRelation:"Father"}});const [submitError,setSubmitError]=useState("");
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==="Escape"&&!isSubmitting)onClose()};document.addEventListener("keydown",key);document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",key);document.body.style.overflow=""}},[isSubmitting,onClose]);
  async function submit(values:FormValues){setSubmitError("");const {data:{user}}=await supabase.auth.getUser();if(!user){setSubmitError("Your session has expired. Please sign in again.");return}const photo=values.photo[0],ext=photo.name.split(".").pop()?.toLowerCase().replace(/[^a-z0-9]/g,"")||"jpg",photoPath=`${user.id}/${crypto.randomUUID()}.${ext}`;const {error:uploadError}=await supabase.storage.from("id-profile-pictures").upload(photoPath,photo,{contentType:photo.type,upsert:false});if(uploadError){setSubmitError(uploadError.message);return}const {photo:_photo,...formData}=values;void _photo;const hindiAddress=[values.hindiHouseNo,values.hindiLocality,`थाना: ${values.hindiPoliceStation}`,values.hindiPostOffice,values.hindiCity,values.hindiState,values.pincode].filter(Boolean).join(", ");const documentData={...formData,language:"Hindi",hindiGuardianRelation:RELATIONSHIP_HINDI[values.guardianRelation],hindiGender:GENDER_HINDI[values.gender],hindiAddress};const {error}=await supabase.rpc("generate_id_record",{p_document_data:documentData,p_photo_path:photoPath});if(error){await supabase.storage.from("id-profile-pictures").remove([photoPath]);setSubmitError(error.message);return}reset();await onCreated()}
  return <div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-slate-950/55 p-4 backdrop-blur-sm sm:p-8" role="dialog" aria-modal="true" aria-labelledby="generate-title" onMouseDown={e=>{if(e.target===e.currentTarget&&!isSubmitting)onClose()}}><form onSubmit={handleSubmit(submit)} className="card my-auto w-full max-w-3xl overflow-hidden"><div className="flex items-start justify-between border-b p-6"><div><h3 id="generate-title" className="text-xl font-bold">Generate ID</h3><p className="mt-1 text-sm text-slate-500">Complete the details below. Submission costs 1 credit (₹10).</p></div><button type="button" className="rounded-lg p-2 hover:bg-slate-100" onClick={onClose} disabled={isSubmitting} aria-label="Close modal"><X className="h-5"/></button></div><div className="max-h-[70vh] overflow-y-auto p-6"><div className="grid gap-5 sm:grid-cols-2">
    <div className="sm:col-span-2"><Field label="Aadhaar number" error={errors.aadhaarNumber?.message}><input className="field" inputMode="numeric" maxLength={12} placeholder="12-digit number" {...register("aadhaarNumber")}/></Field></div>
    <div className="grid gap-3 sm:col-span-2 sm:grid-cols-[10rem_1fr_1fr]"><Field label="Relationship"><select className="field" {...register("guardianRelation")}><option>Father</option><option>Husband</option><option>Guardian</option></select></Field><Field label="Relative name (English)" error={errors.guardianName?.message}><input className="field" placeholder="Enter relative name" {...register("guardianName")}/></Field><HindiField label="Relative name (Hindi)" error={errors.hindiGuardianName?.message} register={register("hindiGuardianName")}/></div>
    <div className="grid gap-3 sm:col-span-2 sm:grid-cols-2"><Field label="Full name (English)" error={errors.fullName?.message}><input className="field" placeholder="Enter full name" {...register("fullName")}/></Field><HindiField label="Full name (Hindi)" error={errors.hindiName?.message} register={register("hindiName")}/></div>
    <Controller name="dob" control={control} render={({field})=><DateOfBirthField value={field.value} onChange={field.onChange} error={errors.dob?.message}/>}/><Field label="Gender"><select className="field" {...register("gender")}><option>Female</option><option>Male</option><option>Other</option></select></Field>
    <div className="sm:col-span-2"><p className="mb-3 text-sm font-bold">Address</p><div className="grid gap-4 sm:grid-cols-2"><BilingualField label="House" englishError={errors.houseNo?.message} hindiError={errors.hindiHouseNo?.message} englishRegister={register("houseNo")} hindiRegister={register("hindiHouseNo")}/><BilingualField label="Locality" englishError={errors.locality?.message} hindiError={errors.hindiLocality?.message} englishRegister={register("locality")} hindiRegister={register("hindiLocality")}/><BilingualField label="Police station" englishError={errors.policeStation?.message} hindiError={errors.hindiPoliceStation?.message} englishRegister={register("policeStation")} hindiRegister={register("hindiPoliceStation")}/><BilingualField label="Post" englishError={errors.postOffice?.message} hindiError={errors.hindiPostOffice?.message} englishRegister={register("postOffice")} hindiRegister={register("hindiPostOffice")}/><BilingualField label="City" englishError={errors.city?.message} hindiError={errors.hindiCity?.message} englishRegister={register("city")} hindiRegister={register("hindiCity")}/><BilingualField label="State" englishError={errors.state?.message} hindiError={errors.hindiState?.message} englishRegister={register("state")} hindiRegister={register("hindiState")}/><Field label="PIN" error={errors.pincode?.message}><input className="field" inputMode="numeric" maxLength={6} {...register("pincode")}/></Field></div></div>
    <div className="sm:col-span-2"><Field label="Profile picture" error={errors.photo?.message as string|undefined}><label className="flex cursor-pointer items-center gap-3 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-4 text-sm text-slate-600 hover:border-indigo-400"><ImagePlus className="h-5 text-indigo-600"/>Choose an image (JPG, PNG or WebP · max 5 MB)<input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" {...register("photo")}/></label></Field></div>
  </div>{submitError&&<p className="mt-5 flex gap-2 rounded-xl bg-red-50 p-3 text-sm text-red-700"><AlertCircle className="h-5 shrink-0"/>{submitError}</p>}</div><div className="flex flex-col-reverse gap-3 border-t bg-slate-50 px-6 py-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm font-semibold text-slate-600">1 credit = ₹10</p><div className="flex gap-3"><button type="button" className="btn border border-slate-200 bg-white" onClick={onClose} disabled={isSubmitting}>Cancel</button><button className="btn btn-primary" disabled={isSubmitting}>{isSubmitting?<Loader2 className="h-5 animate-spin"/>:<FilePlus2 className="h-5"/>}{isSubmitting?"Submitting...":"Generate ID · 1 credit"}</button></div></div></form></div>
}
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label><span className="label">{label}</span>{children}{error&&<span className="error block">{error}</span>}</label>}
function HindiField({label,error,register}:{label:string;error?:string;register:UseFormRegisterReturn}){return <Field label={label} error={error}><input className="field bg-amber-50/60" placeholder="हिंदी में दर्ज करें" lang="hi" {...register}/></Field>}
function BilingualField({label,englishError,hindiError,englishRegister,hindiRegister}:{label:string;englishError?:string;hindiError?:string;englishRegister:UseFormRegisterReturn;hindiRegister:UseFormRegisterReturn}){return <div className="grid gap-2"><Field label={`${label} (English)`} error={englishError}><input className="field" placeholder={`Enter ${label.toLowerCase()}`} {...englishRegister}/></Field><HindiField label={`${label} (Hindi)`} error={hindiError} register={hindiRegister}/></div>}
const RELATIONSHIP_HINDI={Father:"पिता",Husband:"पति",Guardian:"अभिभावक"} as const;
const GENDER_HINDI={Female:"महिला",Male:"पुरुष",Other:"अन्य"} as const;
function DateOfBirthField({value,onChange,error}:{value:string;onChange:(value:string)=>void;error?:string}){
  const selected=value?new Date(`${value}T00:00:00`):null;
  const selectDate=(date:Date|null)=>{if(!date){onChange("");return}const year=date.getFullYear(),month=String(date.getMonth()+1).padStart(2,"0"),day=String(date.getDate()).padStart(2,"0");onChange(`${year}-${month}-${day}`)};
  return <div><label className="label" htmlFor="date-of-birth">Date of birth</label><DatePicker id="date-of-birth" selected={selected} onChange={selectDate} minDate={new Date(1900,0,1)} maxDate={new Date()} showMonthDropdown showYearDropdown dropdownMode="select" dateFormat="dd/MM/yyyy" placeholderText="DD/MM/YYYY" className="field" wrapperClassName="w-full" popperClassName="dob-datepicker" autoComplete="off"/><p className="mt-1 text-xs text-slate-500">Select a date or type DD/MM/YYYY</p>{error&&<span className="error block">{error}</span>}</div>
}
function maskAadhaar(value?:string){return value&&value.length>=4?`XXXX XXXX ${value.slice(-4)}`:"—"}
function formatDate(value?:string){return value?new Date(`${value}T00:00:00`).toLocaleDateString("en-IN"):"—"}
